import type { Block } from 'payload'

export const ComponentPreviewBlock: Block = {
  slug: 'ComponentPreview',
  fields: [
    {
      name: 'component',
      type: 'select',
      options: [
        { label: 'AnimateHeight', value: 'AnimateHeight' },
        { label: 'Banner', value: 'Banner' },
        { label: 'Button', value: 'Button' },
        { label: 'Card', value: 'Card' },
        { label: 'CodeEditor', value: 'CodeEditor' },
        { label: 'Collapsible', value: 'Collapsible' },
        { label: 'CopyToClipboard', value: 'CopyToClipboard' },
        { label: 'DatePicker', value: 'DatePicker' },
        { label: 'Dropzone', value: 'Dropzone' },
        { label: 'ErrorPill', value: 'ErrorPill' },
        { label: 'Gutter', value: 'Gutter' },
        { label: 'Hamburger', value: 'Hamburger' },
        { label: 'Link', value: 'Link' },
        { label: 'ListAndPagination', value: 'ListAndPagination' },
        { label: 'ModalsAndDrawers', value: 'ModalsAndDrawers' },
        { label: 'MotionAndLoading', value: 'MotionAndLoading' },
        { label: 'Pill', value: 'Pill' },
        { label: 'PillSelector', value: 'PillSelector' },
        { label: 'Popup', value: 'Popup' },
        { label: 'ReactSelect', value: 'ReactSelect' },
        { label: 'SearchFilter', value: 'SearchFilter' },
        { label: 'ShimmerEffect', value: 'ShimmerEffect' },
        { label: 'Table', value: 'Table' },
        { label: 'Thumbnail', value: 'Thumbnail' },
        { label: 'TimezonePicker', value: 'TimezonePicker' },
        { label: 'Tooltip', value: 'Tooltip' },
      ],
      required: true,
    },
    {
      name: 'example',
      type: 'select',
      options: [
        { label: 'Actions', value: 'actions' },
        { label: 'Basic', value: 'basic' },
        { label: 'Counts', value: 'counts' },
        { label: 'Confirmation', value: 'confirmation' },
        { label: 'Disabled', value: 'disabled' },
        { label: 'Drawer', value: 'drawer' },
        { label: 'Error', value: 'error' },
        { label: 'Fallback', value: 'fallback' },
        { label: 'Interactive', value: 'interactive' },
        { label: 'Menu', value: 'menu' },
        { label: 'Overlay', value: 'overlay' },
        { label: 'Pagination', value: 'pagination' },
        { label: 'Primary', value: 'primary' },
        { label: 'Progress', value: 'progress' },
        { label: 'Read only', value: 'readOnly' },
        { label: 'Shapes', value: 'shapes' },
        { label: 'Sizes', value: 'sizes' },
        { label: 'States', value: 'states' },
        { label: 'Staggered', value: 'staggered' },
        { label: 'Styles', value: 'styles' },
        { label: 'Variants', value: 'variants' },
      ],
      required: true,
    },
  ],
  interfaceName: 'ComponentPreviewBlock',
  jsx: {
    export: ({ fields }) => ({
      props: {
        component: fields.component,
        example: fields.example,
      },
    }),
    import: ({ props }) => ({
      component: props?.component,
      example: props?.example,
    }),
  },
}
