export const languages = {
  bash: 'Bash',
  css: 'CSS',
  dockerfile: 'Dockerfile',
  env: 'Environment Variables',
  graphql: 'GraphQL',
  html: 'HTML',
  http: 'HTTP',
  js: 'JavaScript',
  json: 'JSON',
  jsx: 'JSX',
  plaintext: 'Plain Text',
  scss: 'SCSS',
  sh: 'Shell',
  text: 'Text',
  ts: 'TypeScript',
  tsx: 'TSX',
  vue: 'Vue',
  yaml: 'YAML',
  yml: 'YAML',
}

export const bannerTypes = {
  alert: 'Alert',
  default: 'Default',
  error: 'Error',
  info: 'Info',
  success: 'Success',
  warning: 'Warning',
}
