import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import postcss from 'postcss'

const filename = fileURLToPath(import.meta.url)
const websiteRoot = path.resolve(path.dirname(filename), '../..')
const previewScope = "[data-payload-preview-version='v4']"
const sourcePath = path.join(
  websiteRoot,
  'preview-runtimes/v4/node_modules/@payloadcms/ui/dist/styles.css',
)
const outputPath = path.join(websiteRoot, 'preview-runtimes/v4/src/generated/scoped.css')
const documentRootPattern = /^(?::root|:host|html|body)(?=$|[.#:[\s>+~])/

const scopeSelector = (selector) => {
  if (selector.includes(previewScope)) {
    return selector
  }

  if (documentRootPattern.test(selector)) {
    return selector.replace(documentRootPattern, previewScope)
  }

  if (selector.startsWith('[data-theme=')) {
    return `${previewScope}${selector}`
  }

  return `${previewScope} ${selector}`
}

const isNestedRule = (rule) => {
  let parent = rule.parent

  while (parent && parent.type !== 'root') {
    if (parent.type === 'rule') {
      return true
    }

    if (parent.type === 'atrule' && /keyframes$/i.test(parent.name)) {
      return true
    }

    parent = parent.parent
  }

  return false
}

const source = await fs.readFile(sourcePath, 'utf8')
const result = await postcss().process(source, { from: sourcePath, to: outputPath })

result.root.walkRules((rule) => {
  if (!isNestedRule(rule)) {
    rule.selectors = rule.selectors.map(scopeSelector)
  }
})

await fs.mkdir(path.dirname(outputPath), { recursive: true })
await fs.writeFile(
  outputPath,
  `/* Generated by src/scripts/generatePreviewStyles.mjs. */\n${result.root.toString()}\n`,
)
