/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    announcements: Announcement;
    'case-studies': CaseStudy;
    'community-help': CommunityHelp;
    docs: Doc;
    media: Media;
    pages: Page;
    posts: Post;
    'reusable-content': ReusableContent;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    footer: Footer;
    'main-menu': MainMenu;
    'top-bar': TopBar;
  };
}
export interface Announcement {
  id: string;
  name?: string | null;
  content: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface CaseStudy {
  id: string;
  title: string;
  introContent: {
    [k: string]: unknown;
  }[];
  featuredImage: string | Media;
  layout?:
    | (
        | {
            ctaFields: {
              richText: {
                [k: string]: unknown;
              }[];
              links?:
                | {
                    link: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'case-studies';
                            value: string | CaseStudy;
                          } | null);
                      url?: string | null;
                      label: string;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            cardGridFields: {
              richText: {
                [k: string]: unknown;
              }[];
              links?:
                | {
                    link: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'case-studies';
                            value: string | CaseStudy;
                          } | null);
                      url?: string | null;
                      label: string;
                    };
                    id?: string | null;
                  }[]
                | null;
              cards?:
                | {
                    title: string;
                    description?: string | null;
                    enableLink?: boolean | null;
                    link?: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'case-studies';
                            value: string | CaseStudy;
                          } | null);
                      url?: string | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            caseStudiesHighlightFields: {
              richText: {
                [k: string]: unknown;
              }[];
              caseStudies: (string | CaseStudy)[];
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudiesHighlight';
          }
        | {
            codeFeatureFields: {
              forceDarkBackground?: boolean | null;
              heading: string;
              richText: {
                [k: string]: unknown;
              }[];
              links?:
                | {
                    link: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'case-studies';
                            value: string | CaseStudy;
                          } | null);
                      url?: string | null;
                      label: string;
                    };
                    id?: string | null;
                  }[]
                | null;
              codeTabs?:
                | {
                    language?: ('none' | 'js' | 'ts') | null;
                    label: string;
                    code: string;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeFeature';
          }
        | {
            contentFields: {
              useLeadingHeader?: boolean | null;
              leadingHeader?:
                | {
                    [k: string]: unknown;
                  }[]
                | null;
              layout?: ('oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns') | null;
              columnOne: {
                [k: string]: unknown;
              }[];
              columnTwo?:
                | {
                    [k: string]: unknown;
                  }[]
                | null;
              columnThree?:
                | {
                    [k: string]: unknown;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            contentGridFields?: {
              forceDarkBackground?: boolean | null;
              useLeadingHeader?: boolean | null;
              leadingHeader?:
                | {
                    [k: string]: unknown;
                  }[]
                | null;
              cells?:
                | {
                    content: {
                      [k: string]: unknown;
                    }[];
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentGrid';
          }
        | {
            formFields: {
              container?: boolean | null;
              richText: {
                [k: string]: unknown;
              }[];
              form: string | Form;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
        | {
            hoverHighlightsFields: {
              richText: {
                [k: string]: unknown;
              }[];
              addRowNumbers?: boolean | null;
              highlights?:
                | {
                    title: string;
                    description: string;
                    media: string | Media;
                    enableLink?: boolean | null;
                    link?: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'case-studies';
                            value: string | CaseStudy;
                          } | null);
                      url?: string | null;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hoverHighlights';
          }
        | {
            linkGridFields?: {
              links?:
                | {
                    link: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'case-studies';
                            value: string | CaseStudy;
                          } | null);
                      url?: string | null;
                      label: string;
                    };
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkGrid';
          }
        | {
            mediaBlockFields: {
              position?: ('default' | 'wide') | null;
              media: string | Media;
              caption?:
                | {
                    [k: string]: unknown;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            mediaContentFields: {
              alignment?: ('contentMedia' | 'mediaContent') | null;
              container?: boolean | null;
              richText: {
                [k: string]: unknown;
              }[];
              enableLink?: boolean | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'case-studies';
                      value: string | CaseStudy;
                    } | null);
                url?: string | null;
                label: string;
              };
              media: string | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaContent';
          }
        | {
            pricingFields?: {
              plans?:
                | {
                    name: string;
                    hasPrice?: boolean | null;
                    price?: string | null;
                    title?: string | null;
                    description?: string | null;
                    enableLink?: boolean | null;
                    link?: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'case-studies';
                            value: string | CaseStudy;
                          } | null);
                      url?: string | null;
                    };
                    features?:
                      | {
                          icon?: ('check' | 'x') | null;
                          feature?: string | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              disclaimer?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            reusableContentBlockFields: {
              reusableContent: string | ReusableContent;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'reusableContentBlock';
          }
        | {
            sliderFields: {
              useLeadingHeader?: boolean | null;
              leadingHeader?:
                | {
                    [k: string]: unknown;
                  }[]
                | null;
              sliderType: 'quoteSlider' | 'imageSlider';
              imageSlides?:
                | {
                    image: string | Media;
                    id?: string | null;
                  }[]
                | null;
              quoteSlides?:
                | {
                    richText: {
                      [k: string]: unknown;
                    }[];
                    quoteDate: string;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            stepsFields: {
              steps: {
                layout?:
                  | (
                      | {
                          codeFeatureFields: {
                            forceDarkBackground?: boolean | null;
                            heading: string;
                            richText: {
                              [k: string]: unknown;
                            }[];
                            links?:
                              | {
                                  link: {
                                    type?: ('reference' | 'custom') | null;
                                    newTab?: boolean | null;
                                    reference?:
                                      | ({
                                          relationTo: 'pages';
                                          value: string | Page;
                                        } | null)
                                      | ({
                                          relationTo: 'posts';
                                          value: string | Post;
                                        } | null)
                                      | ({
                                          relationTo: 'case-studies';
                                          value: string | CaseStudy;
                                        } | null);
                                    url?: string | null;
                                    label: string;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            codeTabs?:
                              | {
                                  language?: ('none' | 'js' | 'ts') | null;
                                  label: string;
                                  code: string;
                                  id?: string | null;
                                }[]
                              | null;
                          };
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'codeFeature';
                        }
                      | {
                          contentFields: {
                            useLeadingHeader?: boolean | null;
                            leadingHeader?:
                              | {
                                  [k: string]: unknown;
                                }[]
                              | null;
                            layout?:
                              | ('oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns')
                              | null;
                            columnOne: {
                              [k: string]: unknown;
                            }[];
                            columnTwo?:
                              | {
                                  [k: string]: unknown;
                                }[]
                              | null;
                            columnThree?:
                              | {
                                  [k: string]: unknown;
                                }[]
                              | null;
                          };
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'content';
                        }
                      | {
                          hoverHighlightsFields: {
                            richText: {
                              [k: string]: unknown;
                            }[];
                            addRowNumbers?: boolean | null;
                            highlights?:
                              | {
                                  title: string;
                                  description: string;
                                  media: string | Media;
                                  enableLink?: boolean | null;
                                  link?: {
                                    type?: ('reference' | 'custom') | null;
                                    newTab?: boolean | null;
                                    reference?:
                                      | ({
                                          relationTo: 'pages';
                                          value: string | Page;
                                        } | null)
                                      | ({
                                          relationTo: 'posts';
                                          value: string | Post;
                                        } | null)
                                      | ({
                                          relationTo: 'case-studies';
                                          value: string | CaseStudy;
                                        } | null);
                                    url?: string | null;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                          };
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'hoverHighlights';
                        }
                      | {
                          stickyHighlightsFields?: {
                            highlights?:
                              | {
                                  richText: {
                                    [k: string]: unknown;
                                  }[];
                                  enableLink?: boolean | null;
                                  link?: {
                                    type?: ('reference' | 'custom') | null;
                                    newTab?: boolean | null;
                                    reference?:
                                      | ({
                                          relationTo: 'pages';
                                          value: string | Page;
                                        } | null)
                                      | ({
                                          relationTo: 'posts';
                                          value: string | Post;
                                        } | null)
                                      | ({
                                          relationTo: 'case-studies';
                                          value: string | CaseStudy;
                                        } | null);
                                    url?: string | null;
                                    label: string;
                                  };
                                  type?: ('code' | 'media') | null;
                                  code?: string | null;
                                  media?: string | Media | null;
                                  id?: string | null;
                                }[]
                              | null;
                          };
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'stickyHighlights';
                        }
                    )[]
                  | null;
                id?: string | null;
              }[];
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            stickyHighlightsFields?: {
              highlights?:
                | {
                    richText: {
                      [k: string]: unknown;
                    }[];
                    enableLink?: boolean | null;
                    link?: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: string | Page;
                          } | null)
                        | ({
                            relationTo: 'posts';
                            value: string | Post;
                          } | null)
                        | ({
                            relationTo: 'case-studies';
                            value: string | CaseStudy;
                          } | null);
                      url?: string | null;
                      label: string;
                    };
                    type?: ('code' | 'media') | null;
                    code?: string | null;
                    media?: string | Media | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'stickyHighlights';
          }
      )[]
    | null;
  slug?: string | null;
  url?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
export interface Media {
  id: string;
  alt: string;
  darkModeFallback?: string | Media | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Page {
  id: string;
  title: string;
  fullTitle?: string | null;
  hero: {
    type: 'default' | 'contentMedia' | 'centeredContent' | 'form' | 'home' | 'livestream' | 'centeredCarousel';
    livestream?: {
      id?: string | null;
      date: string;
      hideBreadcrumbs?: boolean | null;
      richText?:
        | {
            [k: string]: unknown;
          }[]
        | null;
      guests?:
        | {
            name?: string | null;
            link?: string | null;
            image?: string | Media | null;
            id?: string | null;
          }[]
        | null;
    };
    commandLine?: string | null;
    richText?:
      | {
          [k: string]: unknown;
        }[]
      | null;
    description?:
      | {
          [k: string]: unknown;
        }[]
      | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null)
              | ({
                  relationTo: 'case-studies';
                  value: string | CaseStudy;
                } | null);
            url?: string | null;
            label: string;
            appearance?: ('default' | 'primary' | 'secondary') | null;
          };
          id?: string | null;
        }[]
      | null;
    actions?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null)
              | ({
                  relationTo: 'case-studies';
                  value: string | CaseStudy;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
    buttons?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null)
              | ({
                  relationTo: 'case-studies';
                  value: string | CaseStudy;
                } | null);
            url?: string | null;
            label: string;
            appearance?: ('primary' | 'secondary') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: string | Media | null;
    adjectives?:
      | {
          adjective: string;
          id?: string | null;
        }[]
      | null;
    form?: (string | null) | Form;
    logoGroup?: {
      label?: string | null;
      logos?:
        | {
            logo: string | Media;
            id?: string | null;
          }[]
        | null;
    };
    carousel?:
      | {
          image: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  layout: (
    | {
        ctaFields: {
          richText: {
            [k: string]: unknown;
          }[];
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        cardGridFields: {
          richText: {
            [k: string]: unknown;
          }[];
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
          cards?:
            | {
                title: string;
                description?: string | null;
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        caseStudyCardFields?: {
          pixels?: boolean | null;
          cards?:
            | {
                richText: {
                  [k: string]: unknown;
                }[];
                caseStudy: string | CaseStudy;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseStudyCards';
      }
    | {
        caseStudiesHighlightFields: {
          richText: {
            [k: string]: unknown;
          }[];
          caseStudies: (string | CaseStudy)[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseStudiesHighlight';
      }
    | {
        caseStudyParallaxFields?: {
          items?:
            | {
                quote: string;
                author?: string | null;
                logo: string | Media;
                previewImage: string | Media;
                tabLabel: string;
                caseStudy: string | CaseStudy;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseStudyParallax';
      }
    | {
        codeFeatureFields: {
          forceDarkBackground?: boolean | null;
          heading: string;
          richText: {
            [k: string]: unknown;
          }[];
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
          codeTabs?:
            | {
                language?: ('none' | 'js' | 'ts') | null;
                label: string;
                code: string;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'codeFeature';
      }
    | {
        contentFields: {
          useLeadingHeader?: boolean | null;
          leadingHeader?:
            | {
                [k: string]: unknown;
              }[]
            | null;
          layout?: ('oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns') | null;
          columnOne: {
            [k: string]: unknown;
          }[];
          columnTwo?:
            | {
                [k: string]: unknown;
              }[]
            | null;
          columnThree?:
            | {
                [k: string]: unknown;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        contentGridFields?: {
          forceDarkBackground?: boolean | null;
          useLeadingHeader?: boolean | null;
          leadingHeader?:
            | {
                [k: string]: unknown;
              }[]
            | null;
          cells?:
            | {
                content: {
                  [k: string]: unknown;
                }[];
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentGrid';
      }
    | {
        formFields: {
          container?: boolean | null;
          richText: {
            [k: string]: unknown;
          }[];
          form: string | Form;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'form';
      }
    | {
        hoverHighlightsFields: {
          richText: {
            [k: string]: unknown;
          }[];
          addRowNumbers?: boolean | null;
          highlights?:
            | {
                title: string;
                description: string;
                media: string | Media;
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hoverHighlights';
      }
    | {
        linkGridFields?: {
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'linkGrid';
      }
    | {
        mediaBlockFields: {
          position?: ('default' | 'wide') | null;
          media: string | Media;
          caption?:
            | {
                [k: string]: unknown;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        featuredMediaGalleryFields: {
          background?: ('black' | 'dark') | null;
          alignment?: ('contentMediaGallery' | 'mediaGalleryContent') | null;
          leader?: string | null;
          title: string;
          description: {
            [k: string]: unknown;
          }[];
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
          featuredMediaTabs?:
            | {
                mediaScanline?: boolean | null;
                mediaLabel: string;
                mediaAlignment?: ('center' | 'fill') | null;
                media: string | Media;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuredMediaGallery';
      }
    | {
        mediaContentFields: {
          alignment?: ('contentMedia' | 'mediaContent') | null;
          container?: boolean | null;
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean | null;
          link?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null)
              | ({
                  relationTo: 'case-studies';
                  value: string | CaseStudy;
                } | null);
            url?: string | null;
            label: string;
          };
          media: string | Media;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaContent';
      }
    | {
        pricingFields?: {
          plans?:
            | {
                name: string;
                hasPrice?: boolean | null;
                price?: string | null;
                title?: string | null;
                description?: string | null;
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                };
                features?:
                  | {
                      icon?: ('check' | 'x') | null;
                      feature?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          disclaimer?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricing';
      }
    | {
        reusableContentBlockFields: {
          reusableContent: string | ReusableContent;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'reusableContentBlock';
      }
    | {
        sliderFields: {
          useLeadingHeader?: boolean | null;
          leadingHeader?:
            | {
                [k: string]: unknown;
              }[]
            | null;
          sliderType: 'quoteSlider' | 'imageSlider';
          imageSlides?:
            | {
                image: string | Media;
                id?: string | null;
              }[]
            | null;
          quoteSlides?:
            | {
                richText: {
                  [k: string]: unknown;
                }[];
                quoteDate: string;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'slider';
      }
    | {
        stepsFields: {
          steps: {
            layout?:
              | (
                  | {
                      codeFeatureFields: {
                        forceDarkBackground?: boolean | null;
                        heading: string;
                        richText: {
                          [k: string]: unknown;
                        }[];
                        links?:
                          | {
                              link: {
                                type?: ('reference' | 'custom') | null;
                                newTab?: boolean | null;
                                reference?:
                                  | ({
                                      relationTo: 'pages';
                                      value: string | Page;
                                    } | null)
                                  | ({
                                      relationTo: 'posts';
                                      value: string | Post;
                                    } | null)
                                  | ({
                                      relationTo: 'case-studies';
                                      value: string | CaseStudy;
                                    } | null);
                                url?: string | null;
                                label: string;
                              };
                              id?: string | null;
                            }[]
                          | null;
                        codeTabs?:
                          | {
                              language?: ('none' | 'js' | 'ts') | null;
                              label: string;
                              code: string;
                              id?: string | null;
                            }[]
                          | null;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'codeFeature';
                    }
                  | {
                      contentFields: {
                        useLeadingHeader?: boolean | null;
                        leadingHeader?:
                          | {
                              [k: string]: unknown;
                            }[]
                          | null;
                        layout?:
                          | ('oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns')
                          | null;
                        columnOne: {
                          [k: string]: unknown;
                        }[];
                        columnTwo?:
                          | {
                              [k: string]: unknown;
                            }[]
                          | null;
                        columnThree?:
                          | {
                              [k: string]: unknown;
                            }[]
                          | null;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'content';
                    }
                  | {
                      hoverHighlightsFields: {
                        richText: {
                          [k: string]: unknown;
                        }[];
                        addRowNumbers?: boolean | null;
                        highlights?:
                          | {
                              title: string;
                              description: string;
                              media: string | Media;
                              enableLink?: boolean | null;
                              link?: {
                                type?: ('reference' | 'custom') | null;
                                newTab?: boolean | null;
                                reference?:
                                  | ({
                                      relationTo: 'pages';
                                      value: string | Page;
                                    } | null)
                                  | ({
                                      relationTo: 'posts';
                                      value: string | Post;
                                    } | null)
                                  | ({
                                      relationTo: 'case-studies';
                                      value: string | CaseStudy;
                                    } | null);
                                url?: string | null;
                              };
                              id?: string | null;
                            }[]
                          | null;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hoverHighlights';
                    }
                  | {
                      stickyHighlightsFields?: {
                        highlights?:
                          | {
                              richText: {
                                [k: string]: unknown;
                              }[];
                              enableLink?: boolean | null;
                              link?: {
                                type?: ('reference' | 'custom') | null;
                                newTab?: boolean | null;
                                reference?:
                                  | ({
                                      relationTo: 'pages';
                                      value: string | Page;
                                    } | null)
                                  | ({
                                      relationTo: 'posts';
                                      value: string | Post;
                                    } | null)
                                  | ({
                                      relationTo: 'case-studies';
                                      value: string | CaseStudy;
                                    } | null);
                                url?: string | null;
                                label: string;
                              };
                              type?: ('code' | 'media') | null;
                              code?: string | null;
                              media?: string | Media | null;
                              id?: string | null;
                            }[]
                          | null;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'stickyHighlights';
                    }
                )[]
              | null;
            id?: string | null;
          }[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'steps';
      }
    | {
        stickyHighlightsFields?: {
          highlights?:
            | {
                richText: {
                  [k: string]: unknown;
                }[];
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                type?: ('code' | 'media') | null;
                code?: string | null;
                media?: string | Media | null;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'stickyHighlights';
      }
    | ExampleTabsBlock
  )[];
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  parent?: (string | null) | Page;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
export interface Post {
  id: string;
  title: string;
  image: string | Media;
  excerpt: {
    [k: string]: unknown;
  }[];
  content: (
    | {
        bannerFields: {
          type?: ('default' | 'success' | 'warning' | 'error') | null;
          addCheckmark?: boolean | null;
          content: {
            [k: string]: unknown;
          }[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'banner';
      }
    | {
        blogContentFields: {
          richText: {
            [k: string]: unknown;
          }[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogContent';
      }
    | {
        codeFields: {
          language?: ('none' | 'js' | 'ts') | null;
          code: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'code';
      }
    | {
        blogMarkdownFields: {
          markdown: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogMarkdown';
      }
    | {
        mediaBlockFields: {
          position?: ('default' | 'wide') | null;
          media: string | Media;
          caption?:
            | {
                [k: string]: unknown;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        reusableContentBlockFields: {
          reusableContent: string | ReusableContent;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'reusableContentBlock';
      }
  )[];
  relatedPosts?: (string | Post)[] | null;
  slug?: string | null;
  authors: (string | User)[];
  publishedOn: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
export interface ReusableContent {
  id: string;
  title: string;
  layout: (
    | {
        bannerFields: {
          type?: ('default' | 'success' | 'warning' | 'error') | null;
          addCheckmark?: boolean | null;
          content: {
            [k: string]: unknown;
          }[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'banner';
      }
    | {
        blogContentFields: {
          richText: {
            [k: string]: unknown;
          }[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogContent';
      }
    | {
        blogMarkdownFields: {
          markdown: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogMarkdown';
      }
    | {
        ctaFields: {
          richText: {
            [k: string]: unknown;
          }[];
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        cardGridFields: {
          richText: {
            [k: string]: unknown;
          }[];
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
          cards?:
            | {
                title: string;
                description?: string | null;
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        caseStudyCardFields?: {
          pixels?: boolean | null;
          cards?:
            | {
                richText: {
                  [k: string]: unknown;
                }[];
                caseStudy: string | CaseStudy;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseStudyCards';
      }
    | {
        caseStudiesHighlightFields: {
          richText: {
            [k: string]: unknown;
          }[];
          caseStudies: (string | CaseStudy)[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseStudiesHighlight';
      }
    | {
        caseStudyParallaxFields?: {
          items?:
            | {
                quote: string;
                author?: string | null;
                logo: string | Media;
                previewImage: string | Media;
                tabLabel: string;
                caseStudy: string | CaseStudy;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'caseStudyParallax';
      }
    | {
        codeFields: {
          language?: ('none' | 'js' | 'ts') | null;
          code: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'code';
      }
    | {
        codeFeatureFields: {
          forceDarkBackground?: boolean | null;
          heading: string;
          richText: {
            [k: string]: unknown;
          }[];
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
          codeTabs?:
            | {
                language?: ('none' | 'js' | 'ts') | null;
                label: string;
                code: string;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'codeFeature';
      }
    | {
        contentFields: {
          useLeadingHeader?: boolean | null;
          leadingHeader?:
            | {
                [k: string]: unknown;
              }[]
            | null;
          layout?: ('oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns') | null;
          columnOne: {
            [k: string]: unknown;
          }[];
          columnTwo?:
            | {
                [k: string]: unknown;
              }[]
            | null;
          columnThree?:
            | {
                [k: string]: unknown;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        contentGridFields?: {
          forceDarkBackground?: boolean | null;
          useLeadingHeader?: boolean | null;
          leadingHeader?:
            | {
                [k: string]: unknown;
              }[]
            | null;
          cells?:
            | {
                content: {
                  [k: string]: unknown;
                }[];
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentGrid';
      }
    | ExampleTabsBlock
    | {
        formFields: {
          container?: boolean | null;
          richText: {
            [k: string]: unknown;
          }[];
          form: string | Form;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'form';
      }
    | {
        hoverHighlightsFields: {
          richText: {
            [k: string]: unknown;
          }[];
          addRowNumbers?: boolean | null;
          highlights?:
            | {
                title: string;
                description: string;
                media: string | Media;
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hoverHighlights';
      }
    | {
        linkGridFields?: {
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'linkGrid';
      }
    | {
        mediaBlockFields: {
          position?: ('default' | 'wide') | null;
          media: string | Media;
          caption?:
            | {
                [k: string]: unknown;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | {
        featuredMediaGalleryFields: {
          background?: ('black' | 'dark') | null;
          alignment?: ('contentMediaGallery' | 'mediaGalleryContent') | null;
          leader?: string | null;
          title: string;
          description: {
            [k: string]: unknown;
          }[];
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
          featuredMediaTabs?:
            | {
                mediaScanline?: boolean | null;
                mediaLabel: string;
                mediaAlignment?: ('center' | 'fill') | null;
                media: string | Media;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuredMediaGallery';
      }
    | {
        mediaContentFields: {
          alignment?: ('contentMedia' | 'mediaContent') | null;
          container?: boolean | null;
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean | null;
          link?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null)
              | ({
                  relationTo: 'case-studies';
                  value: string | CaseStudy;
                } | null);
            url?: string | null;
            label: string;
          };
          media: string | Media;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaContent';
      }
    | {
        pricingFields?: {
          plans?:
            | {
                name: string;
                hasPrice?: boolean | null;
                price?: string | null;
                title?: string | null;
                description?: string | null;
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                };
                features?:
                  | {
                      icon?: ('check' | 'x') | null;
                      feature?: string | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          disclaimer?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricing';
      }
    | {
        sliderFields: {
          useLeadingHeader?: boolean | null;
          leadingHeader?:
            | {
                [k: string]: unknown;
              }[]
            | null;
          sliderType: 'quoteSlider' | 'imageSlider';
          imageSlides?:
            | {
                image: string | Media;
                id?: string | null;
              }[]
            | null;
          quoteSlides?:
            | {
                richText: {
                  [k: string]: unknown;
                }[];
                quoteDate: string;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'slider';
      }
    | {
        stepsFields: {
          steps: {
            layout?:
              | (
                  | {
                      codeFeatureFields: {
                        forceDarkBackground?: boolean | null;
                        heading: string;
                        richText: {
                          [k: string]: unknown;
                        }[];
                        links?:
                          | {
                              link: {
                                type?: ('reference' | 'custom') | null;
                                newTab?: boolean | null;
                                reference?:
                                  | ({
                                      relationTo: 'pages';
                                      value: string | Page;
                                    } | null)
                                  | ({
                                      relationTo: 'posts';
                                      value: string | Post;
                                    } | null)
                                  | ({
                                      relationTo: 'case-studies';
                                      value: string | CaseStudy;
                                    } | null);
                                url?: string | null;
                                label: string;
                              };
                              id?: string | null;
                            }[]
                          | null;
                        codeTabs?:
                          | {
                              language?: ('none' | 'js' | 'ts') | null;
                              label: string;
                              code: string;
                              id?: string | null;
                            }[]
                          | null;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'codeFeature';
                    }
                  | {
                      contentFields: {
                        useLeadingHeader?: boolean | null;
                        leadingHeader?:
                          | {
                              [k: string]: unknown;
                            }[]
                          | null;
                        layout?:
                          | ('oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns')
                          | null;
                        columnOne: {
                          [k: string]: unknown;
                        }[];
                        columnTwo?:
                          | {
                              [k: string]: unknown;
                            }[]
                          | null;
                        columnThree?:
                          | {
                              [k: string]: unknown;
                            }[]
                          | null;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'content';
                    }
                  | {
                      hoverHighlightsFields: {
                        richText: {
                          [k: string]: unknown;
                        }[];
                        addRowNumbers?: boolean | null;
                        highlights?:
                          | {
                              title: string;
                              description: string;
                              media: string | Media;
                              enableLink?: boolean | null;
                              link?: {
                                type?: ('reference' | 'custom') | null;
                                newTab?: boolean | null;
                                reference?:
                                  | ({
                                      relationTo: 'pages';
                                      value: string | Page;
                                    } | null)
                                  | ({
                                      relationTo: 'posts';
                                      value: string | Post;
                                    } | null)
                                  | ({
                                      relationTo: 'case-studies';
                                      value: string | CaseStudy;
                                    } | null);
                                url?: string | null;
                              };
                              id?: string | null;
                            }[]
                          | null;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hoverHighlights';
                    }
                  | {
                      stickyHighlightsFields?: {
                        highlights?:
                          | {
                              richText: {
                                [k: string]: unknown;
                              }[];
                              enableLink?: boolean | null;
                              link?: {
                                type?: ('reference' | 'custom') | null;
                                newTab?: boolean | null;
                                reference?:
                                  | ({
                                      relationTo: 'pages';
                                      value: string | Page;
                                    } | null)
                                  | ({
                                      relationTo: 'posts';
                                      value: string | Post;
                                    } | null)
                                  | ({
                                      relationTo: 'case-studies';
                                      value: string | CaseStudy;
                                    } | null);
                                url?: string | null;
                                label: string;
                              };
                              type?: ('code' | 'media') | null;
                              code?: string | null;
                              media?: string | Media | null;
                              id?: string | null;
                            }[]
                          | null;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'stickyHighlights';
                    }
                )[]
              | null;
            id?: string | null;
          }[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'steps';
      }
    | {
        stickyHighlightsFields?: {
          highlights?:
            | {
                richText: {
                  [k: string]: unknown;
                }[];
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null)
                    | ({
                        relationTo: 'case-studies';
                        value: string | CaseStudy;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                type?: ('code' | 'media') | null;
                code?: string | null;
                media?: string | Media | null;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'stickyHighlights';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
export interface ExampleTabsBlock {
  content?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  tabs: {
    label: string;
    content?:
      | {
          [k: string]: unknown;
        }[]
      | null;
    examples: (CodeExampleBlock | MediaExampleBlock)[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'exampleTabs';
}
export interface CodeExampleBlock {
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CodeExampleBlock';
}
export interface MediaExampleBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'MediaExampleBlock';
}
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            message?:
              | {
                  [k: string]: unknown;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  leader: {
    [k: string]: unknown;
  }[];
  hubSpotFormID?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  twitter?: string | null;
  photo?: string | Media | null;
  roles: ('admin' | 'public')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface CommunityHelp {
  id: string;
  title?: string | null;
  communityHelpType?: ('discord' | 'github') | null;
  githubID?: string | null;
  discordID?: string | null;
  communityHelpJSON:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  introDescription?: string | null;
  slug?: string | null;
  helpful?: boolean | null;
  relatedDocs?: (string | Doc)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface Doc {
  id: string;
  title: string;
  description?: string | null;
  keywords?: string | null;
  headings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  content?: string | null;
  path?: string | null;
  topic?: string | null;
  slug?: string | null;
  label?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'case-studies';
          value: string | CaseStudy;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Footer {
  id: string;
  columns?:
    | {
        navItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'case-studies';
                      value: string | CaseStudy;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface MainMenu {
  id: string;
  tabs?:
    | {
        label: string;
        description?: string | null;
        navItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'case-studies';
                      value: string | CaseStudy;
                    } | null);
                url?: string | null;
                label: string;
              };
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface TopBar {
  id: string;
  starText?: {
    desktop?:
      | {
          [k: string]: unknown;
        }[]
      | null;
    mobile?:
      | {
          [k: string]: unknown;
        }[]
      | null;
  };
  announcement?: (string | null) | Announcement;
  updatedAt?: string | null;
  createdAt?: string | null;
}