/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    announcements: Announcement;
    'case-studies': CaseStudy;
    'community-help': CommunityHelp;
    media: Media;
    pages: Page;
    posts: Post;
    'reusable-content': ReusableContent;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
  };
  globals: {
    footer: Footer;
    'main-menu': MainMenu;
  };
}
export interface Announcement {
  id: string;
  name?: string;
  content: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface CaseStudy {
  id: string;
  title: string;
  introContent: {
    [k: string]: unknown;
  }[];
  featuredImage: string | Media;
  layout?: (
    | {
        ctaFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          feature: 'none' | 'cpa';
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        cardGridFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
          cards?: {
            title: string;
            description?: string;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cardGrid';
      }
    | {
        caseStudiesHighlightFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          caseStudies: string[] | CaseStudy[];
        };
        id?: string;
        blockName?: string;
        blockType: 'caseStudiesHighlight';
      }
    | {
        codeFeatureFields?: {
          disableBlockSpacing?: boolean;
          heading: string;
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference:
              | {
                  value: string | Page;
                  relationTo: 'pages';
                }
              | {
                  value: string | Post;
                  relationTo: 'posts';
                }
              | {
                  value: string | CaseStudy;
                  relationTo: 'case-studies';
                };
            url: string;
            label: string;
            appearance?: 'default' | 'primary' | 'secondary';
          };
          language?: 'none' | 'js' | 'ts';
          label?: string;
          code: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'codeFeature';
      }
    | {
        contentFields?: {
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          layout?: 'oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns';
          columnOne: {
            [k: string]: unknown;
          }[];
          columnTwo: {
            [k: string]: unknown;
          }[];
          columnThree: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        contentGridFields?: {
          forceDarkBackground?: boolean;
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          cells?: {
            content: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'contentGrid';
      }
    | {
        formFields?: {
          container?: boolean;
          richText: {
            [k: string]: unknown;
          }[];
          form: string | Form;
        };
        id?: string;
        blockName?: string;
        blockType: 'form';
      }
    | {
        hoverHighlightsFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          addRowNumbers?: boolean;
          highlights?: {
            title: string;
            description: string;
            media: string | Media;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'hoverHighlights';
      }
    | {
        linkGridFields?: {
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'linkGrid';
      }
    | {
        mediaBlockFields?: {
          position?: 'default' | 'wide';
          media: string | Media;
          caption?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
    | {
        mediaContentFields?: {
          alignment?: 'contentMedia' | 'mediaContent';
          container?: boolean;
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference:
              | {
                  value: string | Page;
                  relationTo: 'pages';
                }
              | {
                  value: string | Post;
                  relationTo: 'posts';
                }
              | {
                  value: string | CaseStudy;
                  relationTo: 'case-studies';
                };
            url: string;
            label: string;
          };
          media: string | Media;
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaContent';
      }
    | {
        pricingFields?: {
          plans?: {
            name: string;
            hasPrice?: boolean;
            price: string;
            title: string;
            description?: string;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            features?: {
              icon?: 'check' | 'x';
              feature?: string;
              id?: string;
            }[];
            id?: string;
          }[];
          disclaimer?: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'pricing';
      }
    | {
        reusableContentBlockFields?: {
          reusableContent: string | ReusableContent;
        };
        id?: string;
        blockName?: string;
        blockType: 'reusableContentBlock';
      }
    | {
        sliderFields?: {
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          sliderType: 'quoteSlider' | 'imageSlider';
          imageSlides: {
            image: string | Media;
            id?: string;
          }[];
          quoteSlides: {
            richText: {
              [k: string]: unknown;
            }[];
            quoteDate: string;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'slider';
      }
    | {
        stepsFields?: {
          steps: {
            layout?: (
              | {
                  codeFeatureFields?: {
                    disableBlockSpacing?: boolean;
                    heading: string;
                    richText: {
                      [k: string]: unknown;
                    }[];
                    enableLink?: boolean;
                    link?: {
                      type?: 'reference' | 'custom';
                      newTab?: boolean;
                      reference:
                        | {
                            value: string | Page;
                            relationTo: 'pages';
                          }
                        | {
                            value: string | Post;
                            relationTo: 'posts';
                          }
                        | {
                            value: string | CaseStudy;
                            relationTo: 'case-studies';
                          };
                      url: string;
                      label: string;
                      appearance?: 'default' | 'primary' | 'secondary';
                    };
                    language?: 'none' | 'js' | 'ts';
                    label?: string;
                    code: string;
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'codeFeature';
                }
              | {
                  contentFields?: {
                    useLeadingHeader?: boolean;
                    leadingHeader: {
                      [k: string]: unknown;
                    }[];
                    layout?: 'oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns';
                    columnOne: {
                      [k: string]: unknown;
                    }[];
                    columnTwo: {
                      [k: string]: unknown;
                    }[];
                    columnThree: {
                      [k: string]: unknown;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'content';
                }
              | {
                  hoverHighlightsFields?: {
                    richText: {
                      [k: string]: unknown;
                    }[];
                    addRowNumbers?: boolean;
                    highlights?: {
                      title: string;
                      description: string;
                      media: string | Media;
                      enableLink?: boolean;
                      link?: {
                        type?: 'reference' | 'custom';
                        newTab?: boolean;
                        reference:
                          | {
                              value: string | Page;
                              relationTo: 'pages';
                            }
                          | {
                              value: string | Post;
                              relationTo: 'posts';
                            }
                          | {
                              value: string | CaseStudy;
                              relationTo: 'case-studies';
                            };
                        url: string;
                      };
                      id?: string;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'hoverHighlights';
                }
              | {
                  stickyHighlightsFields?: {
                    highlights?: {
                      richText: {
                        [k: string]: unknown;
                      }[];
                      enableLink?: boolean;
                      link?: {
                        type?: 'reference' | 'custom';
                        newTab?: boolean;
                        reference:
                          | {
                              value: string | Page;
                              relationTo: 'pages';
                            }
                          | {
                              value: string | Post;
                              relationTo: 'posts';
                            }
                          | {
                              value: string | CaseStudy;
                              relationTo: 'case-studies';
                            };
                        url: string;
                        label: string;
                      };
                      type?: 'code' | 'media';
                      code: string;
                      media: string | Media;
                      id?: string;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'stickyHighlights';
                }
            )[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'steps';
      }
    | {
        stickyHighlightsFields?: {
          highlights?: {
            richText: {
              [k: string]: unknown;
            }[];
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            type?: 'code' | 'media';
            code: string;
            media: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'stickyHighlights';
      }
  )[];
  slug?: string;
  url?: string;
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface Media {
  id: string;
  alt: string;
  darkModeFallback?: string | Media;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
export interface Page {
  id: string;
  title: string;
  fullTitle?: string;
  hero?: {
    type: 'default' | 'contentMedia' | 'form' | 'home' | 'livestream';
    livestream?: {
      id?: string;
      date: string;
      hideBreadcrumbs?: boolean;
      richText?: {
        [k: string]: unknown;
      }[];
      guests?: {
        name?: string;
        link?: string;
        image?: string | Media;
        id?: string;
      }[];
    };
    richText?: {
      [k: string]: unknown;
    }[];
    sidebarContent?: {
      [k: string]: unknown;
    }[];
    links?: {
      link?: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | Post;
              relationTo: 'posts';
            }
          | {
              value: string | CaseStudy;
              relationTo: 'case-studies';
            };
        url: string;
        label: string;
        appearance?: 'default' | 'primary' | 'secondary';
      };
      id?: string;
    }[];
    actions?: {
      link?: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | Post;
              relationTo: 'posts';
            }
          | {
              value: string | CaseStudy;
              relationTo: 'case-studies';
            };
        url: string;
        label: string;
      };
      id?: string;
    }[];
    buttons?: {
      link?: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | Post;
              relationTo: 'posts';
            }
          | {
              value: string | CaseStudy;
              relationTo: 'case-studies';
            };
        url: string;
        label: string;
        appearance?: 'primary' | 'secondary';
      };
      id?: string;
    }[];
    media: string | Media;
    adjectives?: {
      adjective: string;
      id?: string;
    }[];
    form?: string | Form;
  };
  layout: (
    | {
        ctaFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          feature: 'none' | 'cpa';
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        cardGridFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
          cards?: {
            title: string;
            description?: string;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cardGrid';
      }
    | {
        caseStudyCardFields?: {
          cards?: {
            richText: {
              [k: string]: unknown;
            }[];
            caseStudy: string | CaseStudy;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'caseStudyCards';
      }
    | {
        caseStudiesHighlightFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          caseStudies: string[] | CaseStudy[];
        };
        id?: string;
        blockName?: string;
        blockType: 'caseStudiesHighlight';
      }
    | {
        codeFeatureFields?: {
          disableBlockSpacing?: boolean;
          heading: string;
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference:
              | {
                  value: string | Page;
                  relationTo: 'pages';
                }
              | {
                  value: string | Post;
                  relationTo: 'posts';
                }
              | {
                  value: string | CaseStudy;
                  relationTo: 'case-studies';
                };
            url: string;
            label: string;
            appearance?: 'default' | 'primary' | 'secondary';
          };
          language?: 'none' | 'js' | 'ts';
          label?: string;
          code: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'codeFeature';
      }
    | {
        contentFields?: {
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          layout?: 'oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns';
          columnOne: {
            [k: string]: unknown;
          }[];
          columnTwo: {
            [k: string]: unknown;
          }[];
          columnThree: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        contentGridFields?: {
          forceDarkBackground?: boolean;
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          cells?: {
            content: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'contentGrid';
      }
    | {
        formFields?: {
          container?: boolean;
          richText: {
            [k: string]: unknown;
          }[];
          form: string | Form;
        };
        id?: string;
        blockName?: string;
        blockType: 'form';
      }
    | {
        hoverHighlightsFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          addRowNumbers?: boolean;
          highlights?: {
            title: string;
            description: string;
            media: string | Media;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'hoverHighlights';
      }
    | {
        linkGridFields?: {
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'linkGrid';
      }
    | {
        mediaBlockFields?: {
          position?: 'default' | 'wide';
          media: string | Media;
          caption?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
    | {
        mediaContentFields?: {
          alignment?: 'contentMedia' | 'mediaContent';
          container?: boolean;
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference:
              | {
                  value: string | Page;
                  relationTo: 'pages';
                }
              | {
                  value: string | Post;
                  relationTo: 'posts';
                }
              | {
                  value: string | CaseStudy;
                  relationTo: 'case-studies';
                };
            url: string;
            label: string;
          };
          media: string | Media;
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaContent';
      }
    | {
        pricingFields?: {
          plans?: {
            name: string;
            hasPrice?: boolean;
            price: string;
            title: string;
            description?: string;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            features?: {
              icon?: 'check' | 'x';
              feature?: string;
              id?: string;
            }[];
            id?: string;
          }[];
          disclaimer?: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'pricing';
      }
    | {
        reusableContentBlockFields?: {
          reusableContent: string | ReusableContent;
        };
        id?: string;
        blockName?: string;
        blockType: 'reusableContentBlock';
      }
    | {
        sliderFields?: {
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          sliderType: 'quoteSlider' | 'imageSlider';
          imageSlides: {
            image: string | Media;
            id?: string;
          }[];
          quoteSlides: {
            richText: {
              [k: string]: unknown;
            }[];
            quoteDate: string;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'slider';
      }
    | {
        stepsFields?: {
          steps: {
            layout?: (
              | {
                  codeFeatureFields?: {
                    disableBlockSpacing?: boolean;
                    heading: string;
                    richText: {
                      [k: string]: unknown;
                    }[];
                    enableLink?: boolean;
                    link?: {
                      type?: 'reference' | 'custom';
                      newTab?: boolean;
                      reference:
                        | {
                            value: string | Page;
                            relationTo: 'pages';
                          }
                        | {
                            value: string | Post;
                            relationTo: 'posts';
                          }
                        | {
                            value: string | CaseStudy;
                            relationTo: 'case-studies';
                          };
                      url: string;
                      label: string;
                      appearance?: 'default' | 'primary' | 'secondary';
                    };
                    language?: 'none' | 'js' | 'ts';
                    label?: string;
                    code: string;
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'codeFeature';
                }
              | {
                  contentFields?: {
                    useLeadingHeader?: boolean;
                    leadingHeader: {
                      [k: string]: unknown;
                    }[];
                    layout?: 'oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns';
                    columnOne: {
                      [k: string]: unknown;
                    }[];
                    columnTwo: {
                      [k: string]: unknown;
                    }[];
                    columnThree: {
                      [k: string]: unknown;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'content';
                }
              | {
                  hoverHighlightsFields?: {
                    richText: {
                      [k: string]: unknown;
                    }[];
                    addRowNumbers?: boolean;
                    highlights?: {
                      title: string;
                      description: string;
                      media: string | Media;
                      enableLink?: boolean;
                      link?: {
                        type?: 'reference' | 'custom';
                        newTab?: boolean;
                        reference:
                          | {
                              value: string | Page;
                              relationTo: 'pages';
                            }
                          | {
                              value: string | Post;
                              relationTo: 'posts';
                            }
                          | {
                              value: string | CaseStudy;
                              relationTo: 'case-studies';
                            };
                        url: string;
                      };
                      id?: string;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'hoverHighlights';
                }
              | {
                  stickyHighlightsFields?: {
                    highlights?: {
                      richText: {
                        [k: string]: unknown;
                      }[];
                      enableLink?: boolean;
                      link?: {
                        type?: 'reference' | 'custom';
                        newTab?: boolean;
                        reference:
                          | {
                              value: string | Page;
                              relationTo: 'pages';
                            }
                          | {
                              value: string | Post;
                              relationTo: 'posts';
                            }
                          | {
                              value: string | CaseStudy;
                              relationTo: 'case-studies';
                            };
                        url: string;
                        label: string;
                      };
                      type?: 'code' | 'media';
                      code: string;
                      media: string | Media;
                      id?: string;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'stickyHighlights';
                }
            )[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'steps';
      }
    | {
        stickyHighlightsFields?: {
          highlights?: {
            richText: {
              [k: string]: unknown;
            }[];
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            type?: 'code' | 'media';
            code: string;
            media: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'stickyHighlights';
      }
  )[];
  slug?: string;
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  parent?: string | Page;
  breadcrumbs?: {
    doc?: string | Page;
    url?: string;
    label?: string;
    id?: string;
  }[];
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface Post {
  id: string;
  title: string;
  image: string | Media;
  excerpt: {
    [k: string]: unknown;
  }[];
  content: (
    | {
        bannerFields?: {
          type?: 'default' | 'success' | 'warning' | 'error';
          addCheckmark?: boolean;
          content: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'banner';
      }
    | {
        blogContentFields?: {
          richText: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'blogContent';
      }
    | {
        codeFields?: {
          language?: 'none' | 'js' | 'ts';
          code: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'code';
      }
    | {
        blogMarkdownFields?: {
          markdown: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'blogMarkdown';
      }
    | {
        mediaBlockFields?: {
          position?: 'default' | 'wide';
          media: string | Media;
          caption?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
  )[];
  slug?: string;
  author: string | User;
  publishedOn: string;
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  twitter?: string;
  photo?: string | Media;
  roles: ('admin' | 'public')[];
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Form {
  id: string;
  title: string;
  fields?: (
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'text';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'textarea';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        options?: {
          label: string;
          value: string;
          id?: string;
        }[];
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'select';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'email';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'state';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'country';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'number';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        defaultValue?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'checkbox';
      }
    | {
        message?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'message';
      }
  )[];
  submitButtonLabel?: string;
  confirmationType?: 'message' | 'redirect';
  confirmationMessage: {
    [k: string]: unknown;
  }[];
  redirect?: {
    url: string;
  };
  emails?: {
    emailTo?: string;
    cc?: string;
    bcc?: string;
    replyTo?: string;
    emailFrom?: string;
    subject: string;
    message?: {
      [k: string]: unknown;
    }[];
    id?: string;
  }[];
  leader: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface ReusableContent {
  id: string;
  title: string;
  layout: (
    | {
        bannerFields?: {
          type?: 'default' | 'success' | 'warning' | 'error';
          addCheckmark?: boolean;
          content: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'banner';
      }
    | {
        blogContentFields?: {
          richText: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'blogContent';
      }
    | {
        blogMarkdownFields?: {
          markdown: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'blogMarkdown';
      }
    | {
        ctaFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          feature: 'none' | 'cpa';
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        cardGridFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
          cards?: {
            title: string;
            description?: string;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cardGrid';
      }
    | {
        caseStudyCardFields?: {
          cards?: {
            richText: {
              [k: string]: unknown;
            }[];
            caseStudy: string | CaseStudy;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'caseStudyCards';
      }
    | {
        caseStudiesHighlightFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          caseStudies: string[] | CaseStudy[];
        };
        id?: string;
        blockName?: string;
        blockType: 'caseStudiesHighlight';
      }
    | {
        codeFields?: {
          language?: 'none' | 'js' | 'ts';
          code: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'code';
      }
    | {
        codeFeatureFields?: {
          disableBlockSpacing?: boolean;
          heading: string;
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference:
              | {
                  value: string | Page;
                  relationTo: 'pages';
                }
              | {
                  value: string | Post;
                  relationTo: 'posts';
                }
              | {
                  value: string | CaseStudy;
                  relationTo: 'case-studies';
                };
            url: string;
            label: string;
            appearance?: 'default' | 'primary' | 'secondary';
          };
          language?: 'none' | 'js' | 'ts';
          label?: string;
          code: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'codeFeature';
      }
    | {
        contentFields?: {
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          layout?: 'oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns';
          columnOne: {
            [k: string]: unknown;
          }[];
          columnTwo: {
            [k: string]: unknown;
          }[];
          columnThree: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        contentGridFields?: {
          forceDarkBackground?: boolean;
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          cells?: {
            content: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'contentGrid';
      }
    | {
        formFields?: {
          container?: boolean;
          richText: {
            [k: string]: unknown;
          }[];
          form: string | Form;
        };
        id?: string;
        blockName?: string;
        blockType: 'form';
      }
    | {
        hoverHighlightsFields?: {
          richText: {
            [k: string]: unknown;
          }[];
          addRowNumbers?: boolean;
          highlights?: {
            title: string;
            description: string;
            media: string | Media;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'hoverHighlights';
      }
    | {
        linkGridFields?: {
          links?: {
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'linkGrid';
      }
    | {
        mediaBlockFields?: {
          position?: 'default' | 'wide';
          media: string | Media;
          caption?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
    | {
        mediaContentFields?: {
          alignment?: 'contentMedia' | 'mediaContent';
          container?: boolean;
          richText: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference:
              | {
                  value: string | Page;
                  relationTo: 'pages';
                }
              | {
                  value: string | Post;
                  relationTo: 'posts';
                }
              | {
                  value: string | CaseStudy;
                  relationTo: 'case-studies';
                };
            url: string;
            label: string;
          };
          media: string | Media;
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaContent';
      }
    | {
        pricingFields?: {
          plans?: {
            name: string;
            hasPrice?: boolean;
            price: string;
            title: string;
            description?: string;
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
            };
            features?: {
              icon?: 'check' | 'x';
              feature?: string;
              id?: string;
            }[];
            id?: string;
          }[];
          disclaimer?: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'pricing';
      }
    | {
        sliderFields?: {
          useLeadingHeader?: boolean;
          leadingHeader: {
            [k: string]: unknown;
          }[];
          sliderType: 'quoteSlider' | 'imageSlider';
          imageSlides: {
            image: string | Media;
            id?: string;
          }[];
          quoteSlides: {
            richText: {
              [k: string]: unknown;
            }[];
            quoteDate: string;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'slider';
      }
    | {
        stepsFields?: {
          steps: {
            layout?: (
              | {
                  codeFeatureFields?: {
                    disableBlockSpacing?: boolean;
                    heading: string;
                    richText: {
                      [k: string]: unknown;
                    }[];
                    enableLink?: boolean;
                    link?: {
                      type?: 'reference' | 'custom';
                      newTab?: boolean;
                      reference:
                        | {
                            value: string | Page;
                            relationTo: 'pages';
                          }
                        | {
                            value: string | Post;
                            relationTo: 'posts';
                          }
                        | {
                            value: string | CaseStudy;
                            relationTo: 'case-studies';
                          };
                      url: string;
                      label: string;
                      appearance?: 'default' | 'primary' | 'secondary';
                    };
                    language?: 'none' | 'js' | 'ts';
                    label?: string;
                    code: string;
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'codeFeature';
                }
              | {
                  contentFields?: {
                    useLeadingHeader?: boolean;
                    leadingHeader: {
                      [k: string]: unknown;
                    }[];
                    layout?: 'oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns';
                    columnOne: {
                      [k: string]: unknown;
                    }[];
                    columnTwo: {
                      [k: string]: unknown;
                    }[];
                    columnThree: {
                      [k: string]: unknown;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'content';
                }
              | {
                  hoverHighlightsFields?: {
                    richText: {
                      [k: string]: unknown;
                    }[];
                    addRowNumbers?: boolean;
                    highlights?: {
                      title: string;
                      description: string;
                      media: string | Media;
                      enableLink?: boolean;
                      link?: {
                        type?: 'reference' | 'custom';
                        newTab?: boolean;
                        reference:
                          | {
                              value: string | Page;
                              relationTo: 'pages';
                            }
                          | {
                              value: string | Post;
                              relationTo: 'posts';
                            }
                          | {
                              value: string | CaseStudy;
                              relationTo: 'case-studies';
                            };
                        url: string;
                      };
                      id?: string;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'hoverHighlights';
                }
              | {
                  stickyHighlightsFields?: {
                    highlights?: {
                      richText: {
                        [k: string]: unknown;
                      }[];
                      enableLink?: boolean;
                      link?: {
                        type?: 'reference' | 'custom';
                        newTab?: boolean;
                        reference:
                          | {
                              value: string | Page;
                              relationTo: 'pages';
                            }
                          | {
                              value: string | Post;
                              relationTo: 'posts';
                            }
                          | {
                              value: string | CaseStudy;
                              relationTo: 'case-studies';
                            };
                        url: string;
                        label: string;
                      };
                      type?: 'code' | 'media';
                      code: string;
                      media: string | Media;
                      id?: string;
                    }[];
                  };
                  id?: string;
                  blockName?: string;
                  blockType: 'stickyHighlights';
                }
            )[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'steps';
      }
    | {
        stickyHighlightsFields?: {
          highlights?: {
            richText: {
              [k: string]: unknown;
            }[];
            enableLink?: boolean;
            link?: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Post;
                    relationTo: 'posts';
                  }
                | {
                    value: string | CaseStudy;
                    relationTo: 'case-studies';
                  };
              url: string;
              label: string;
            };
            type?: 'code' | 'media';
            code: string;
            media: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'stickyHighlights';
      }
  )[];
  createdAt: string;
  updatedAt: string;
}
export interface CommunityHelp {
  id: string;
  title?: string;
  communityHelpType?: 'discord' | 'github';
  githubID?: string;
  discordID?: string;
  communityHelpJSON:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  slug?: string;
  createdAt: string;
  updatedAt: string;
}
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?: {
    field: string;
    value: string;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface Footer {
  id: string;
  columns?: {
    navItems?: {
      link?: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | Post;
              relationTo: 'posts';
            }
          | {
              value: string | CaseStudy;
              relationTo: 'case-studies';
            };
        url: string;
        label: string;
      };
      id?: string;
    }[];
    id?: string;
  }[];
}
export interface MainMenu {
  id: string;
  navItems?: {
    link?: {
      type?: 'reference' | 'custom';
      newTab?: boolean;
      reference:
        | {
            value: string | Page;
            relationTo: 'pages';
          }
        | {
            value: string | Post;
            relationTo: 'posts';
          }
        | {
            value: string | CaseStudy;
            relationTo: 'case-studies';
          };
      url: string;
      label: string;
    };
    id?: string;
  }[];
}
